In [1]:
import numpy as np

# **Creating Numpy Arrays**

---



# **1D Array**

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


## **From User Input**

In [3]:
"""
l = []
for i in range(1,5):
  no = int(input("Enter elements of numpy array"))
  l.append(no)
print(l)
"""

'\nl = []\nfor i in range(1,5):\n  no = int(input("Enter elements of numpy array"))\n  l.append(no)\nprint(l)\n'

# **2D Array**

In [4]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print("Dimension of Arrar :",arr.ndim,"D")

[[1 2 3 4]
 [5 6 7 8]]
Dimension of Arrar : 2 D


# **3D Array**

In [5]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr1)
print("Dimension of Arrar :",arr1.ndim,"D")

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimension of Arrar : 3 D


# **Special Numpy Arrays**

---



## **Zeros**

In [6]:
zeroarr = np.zeros(4)
print(zeroarr)

[0. 0. 0. 0.]


In [7]:
zeroarr2 = np.zeros((3,4))   # 3 rows and 4 columns
print(zeroarr2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## **Ones**

In [8]:
onesarr1 = np.ones(3)
print(onesarr1)

[1. 1. 1.]


In [9]:
onesarr2 = np.ones((3,3))    # 3 rows and 3 columns
print(onesarr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## **Range**






In [10]:
rangearr1 = np.arange(4)    #Sequence me de dega
print(rangearr1)

[0 1 2 3]


In [11]:
rangearr2 = np.arange(0,6)    #Sequence me de dega, start se aik kam last tak
print(rangearr2)

[0 1 2 3 4 5]


## **1 in Diagonal**

In [12]:
diaarr = np.eye(3)    # 3*3 ke matrix ke diagonal me 1 dedega baqi 0
print(diaarr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## **Linspace**

> (0,10,6) 0-start, 10-end, 6-no. of elements



In [13]:
linarr = np.linspace(0,10,6)
print(linarr)

[ 0.  2.  4.  6.  8. 10.]


In [14]:
linarr1 = np.linspace(0,100,51)
print(linarr1)

[  0.   2.   4.   6.   8.  10.  12.  14.  16.  18.  20.  22.  24.  26.
  28.  30.  32.  34.  36.  38.  40.  42.  44.  46.  48.  50.  52.  54.
  56.  58.  60.  62.  64.  66.  68.  70.  72.  74.  76.  78.  80.  82.
  84.  86.  88.  90.  92.  94.  96.  98. 100.]


# **Creating Numpy Arrays with random numbers**

---



## **rand()**

```
# generate numbers between 0 and 1
```



In [15]:
rand_arr = np.random.rand(3)
print(rand_arr)

[0.85213347 0.54351469 0.68339582]


## **randn()**

```
# Generate numbers closed to zero [+ve and -ve] both
```



In [16]:
randn_arr = np.random.randn(5)
print(randn_arr)

[ 0.20913959 -1.67413659  0.211783    1.57952572  0.81605861]


## **ranf()**

```
# Generate numbers between 0.0 and 1.0 (same as rand)

```



In [17]:
ranf_arr = np.random.ranf(4)
print(ranf_arr)

[0.14507423 0.35401886 0.9589006  0.38586219]


## **randint()**
(start, end, no)
```
# Generate n number of elements from start to end
```



In [18]:
randint_arr = np.random.randint(2,20,10)
print(randint_arr)

[ 9 14 19  4 10 16  4  7  6  9]


# **Checking the Datatype**

---



In [19]:
arr_int = np.array([1,2,3,4])
print(arr_int.dtype)

int64


## **Array with defined datatype**

In [20]:
arr_S = np.array([1,2,3,4],dtype = "S")
print(arr_S.dtype)

|S1


## **String Datatype**

In [21]:
arr_st = np.array(["S","H","A","Y","A","N"])
print(arr_st.dtype)

<U1


# **Changing the Datatype**

---



In [22]:
arr4 = np.array([1,2,3,4], dtype = np.int8)
print(arr4.dtype)

arr5 = np.array([1,2,3,4], dtype = "f")
print(arr5.dtype)

int8
float32


## **Changing with astype function**

In [23]:
arr6 = np.array([1,2,3,4])
new = arr6.astype(float)
print(arr6)
print(new)
print(new.dtype)

[1 2 3 4]
[1. 2. 3. 4.]
float64


# ***Arithmetic Operations in Numpy Arrays***

---



## **Addition**

In [24]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
print(var1+var2)

[ 6  8 10 12]


In [25]:
print(var1+2)

[3 4 5 6]


In [26]:
print(var2+5)

[10 11 12 13]


## **Subtraction**

In [27]:
print(var2-var1)

[4 4 4 4]


In [28]:
print(var2-1)

[4 5 6 7]


## **Multiplication**

In [29]:
print(var1*var2)

[ 5 12 21 32]


## **Division**

In [30]:
print(var2/2)

[2.5 3.  3.5 4. ]


## **Modulus**

In [31]:
print(var1 % var2)

[1 2 3 4]


## **Power**

In [32]:
print(var1 ** var2)

[    1    64  2187 65536]


# **Operations using functions**

---



In [33]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
add = np.add(var1,var2)
print(add)

[ 6  8 10 12]


In [34]:
sub  = np.subtract(var2,var1)
print(sub)

[4 4 4 4]


In [35]:
mul = np.multiply(var1,var2)
print(mul)

[ 5 12 21 32]


In [36]:
div = np.divide(var2,var1)
print(div)

[5.         3.         2.33333333 2.        ]


In [37]:
mod = np.mod(var1,var2)
print(mod)

[1 2 3 4]


In [38]:
pow = np.power(var1,var2)
print(pow)

[    1    64  2187 65536]


# ***Arithmetic Functions***

---



## **Min/Max**

In [39]:
var = np.array([1,2,4,9,5,6,8,7])
print("Minimum",np.min(var))
print("Maximum",np.max(var))

Minimum 1
Maximum 9


## **np.argmin / np.argmax**

> index of min / max



In [40]:
var = np.array([1,2,4,9,5,6,8,7])
print("Minimum",np.min(var),"at Index",np.argmin(var))
print("Maximum",np.max(var),"at Index",np.argmax(var))

Minimum 1 at Index 0
Maximum 9 at Index 3


## **Min / Max in 2D Array**

In [41]:
var2d = np.array([[1,2,3,4],[5,6,7,8]])
print("axis 0 / Column")
print("Minimum",np.min(var2d,axis = 0))
print("Maximum",np.max(var2d,axis = 0))

print("Minimum",np.min(var2d,axis = 1))
print("Maximum",np.max(var2d,axis = 1))

axis 0 / Column
Minimum [1 2 3 4]
Maximum [5 6 7 8]
Minimum [1 5]
Maximum [4 8]


## **np.sqrt**

In [42]:
var = np.array([4,16,36])
print(np.sqrt(var))

[2. 4. 6.]


## **Sin(x)**

In [43]:
print(np.sin(var))

[-0.7568025  -0.28790332 -0.99177885]


## **Cos(x)**

In [44]:
print(np.cos(var))

[-0.65364362 -0.95765948 -0.12796369]


# ***Shape and Reshaping***

---



> answers in rows and columns like below is 2*4 array (2 rows and 4 columns)



## **Shape**

In [45]:
var = np.array([[1,2,3,4],[5,6,7,8]])
print(var.shape)

(2, 4)


In [46]:
var = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(var.shape)

(3, 3)


## **Reshape**

> var.reshape(3,3) iska mtlb hai ke jo bhi ham shape specify karenge, tu array us shape me divide hojaega



In [47]:
var = np.array([1,2,3,4,5,6,7,8,9])
print(var.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# ***Broadcasting in Numpy Arrays***


---


> 2 different shapes ke arrays par arithmetic operations perform karna

Broadcasting Rules


*   Same Dimension
*   (1 x 3) . (3 x 1) ye bhi hojaega



In [48]:
var1 = np.array(([1,2,3]))
var2 = np.array([[1],[2],[3]])

print(var1.shape)
print(var2.shape)

print(var1 + var2)

(3,)
(3, 1)
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [49]:
var1 = np.array([[1],[2]])
var2 = np.array([[1,2,3],[1,2,3]])

print(var1+var2)

[[2 3 4]
 [3 4 5]]


# ***Indexing***

---



## **1D Array**

In [50]:
var = np.array([1,2,3,4,5,6,7,8,9])
for i in range(0, len(var)):
  print("Index :",i,"element :",var[i])

Index : 0 element : 1
Index : 1 element : 2
Index : 2 element : 3
Index : 3 element : 4
Index : 4 element : 5
Index : 5 element : 6
Index : 6 element : 7
Index : 7 element : 8
Index : 8 element : 9


## **2D Array**

```
[[1 2 3]
 [4 5 6]]

 in this first array is index 0, 2nd index 1 and inside both starting from 0 to onwards
```



In [51]:
var = np.array([[1,2,3],[4,5,6]])
print(var[1,2])

6


## **3D Array**


*   First number → block (depth) index
*   Second number → row index in that block
*   Third number → column index in that row

In [52]:
var = np.array([[[1,2],[3,4]]])
print(var[0,1,1])

4


# **Slicing**

---



## **1D Array**


*   start → slice ka starting index (inclusive)
*   stop → slice ka ending index (exclusive)
*   step → kitne index skip karke agla element lena hai





In [53]:
var = np.array([1,2,3,4,5,6,7,8,9])
print(var[1:5:1])

[2 3 4 5]


## **2D Array**

*   0 → row index (yani sirf row 0 lo)
*   2:3:1 → columns ka slice (start=2, stop=3, step=1)



In [54]:
var = np.array([[1,2,3],[4,5,6]])
print(var[0,0:3:1])

[1 2 3]


## **3D Array**

In [55]:
var = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(var[0,0,0:3])

[1 2 3]


# ***Numpy Iteration***

---



## **1D Array**

In [56]:
var = np.array([1,2,3,4,5])
for i in var:
  print(i)

1
2
3
4
5


## **2D Array**

In [57]:
var = np.array([[1,2,3,4],[5,6,7,8]])
for i in var:
  print(i)

for j in var:
  for k in j:
    print(k)

[1 2 3 4]
[5 6 7 8]
1
2
3
4
5
6
7
8


## **3D Array**

In [58]:
var = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in var:
  for j in i:
    for k in j:
      print(k)

1
2
3
4
5
6
7
8
9


# ***Iterate Using Function***

---

asaan tariqa hai, nested loops nhi lagane parenge

*   np.nditer()
*   np.udenumerate()   (index ke sath dega)



In [59]:
var = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(var):
  print(i)

1
2
3
4
5
6
7
8
9


In [60]:
var = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i, d in np.ndenumerate(var):
  print(i, d)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 2, 0) 7
(0, 2, 1) 8
(0, 2, 2) 9


# **Copy vs View**

---



# **Copy**

In [65]:
var = np.array([1,2,3,4])
copy = var.copy()
print("Original :",var)
print("Copy :",copy)

Original : [1 2 3 4]
Copy : [1 2 3 4]


# **View**

In [67]:
var = np.array([1,2,3,4])
view = var.view()
print("Original :",var)
print("View :",view)

Original : [1 2 3 4]
Copy : [1 2 3 4]


# **Difference between Copy and View**




### **Copy**

> Original me kuch changes karenge tu copy me kuch change nhi hoga
### **View**
> Original me changes karenge tu view wali copy me bhi update hojaegi





### **Copy**

In [70]:
var = np.array([1,2,3,4])
copy = var.copy()

var[1] = 100
print("Original after change:",var)
print("Copy after change:",copy)

Original after change: [  1 100   3   4]
Copy after change: [1 2 3 4]


### **View**

In [71]:
var = np.array([1,2,3,4])
view = var.view()

var[1] = 100
print("Original after change:",var)
print("View after change:",view)

Original after change: [  1 100   3   4]
View after change: [  1 100   3   4]


# **Join and Split Array**

---



# **Join Array**



> Concatenate

---





## **1D Array**

In [74]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])

new_arr = np.concatenate((var1,var2))
print(new_arr)

[1 2 3 4 5 6 7 8]


## **2D Array**

In [81]:
var1 = np.array([[1,2],[3,4]])
var2 = np.array([[5,6],[7,8]])

new_arr1 = np.concatenate((var1,var2),axis = 0)
new_arr2 = np.concatenate((var1,var2),axis = 1)
print("Concantenate w.r.t axis 0 :\n",new_arr1)
print("\nConcantenate w.r.t axis 1 : \n",new_arr2)

Concantenate w.r.t axis 0 :
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concantenate w.r.t axis 1 : 
 [[1 2 5 6]
 [3 4 7 8]]


# **Split Array**



> break one array into multiple



## **1D Array**

In [88]:
var1 = np.array([1,2,3,4,5,6])
var_new = np.split(var1, 2)
var_new1 = np.split(var1, 3)

print("Split in 2 :",var_new)
print("Split in 3 :",var_new1)

Split in 2 : [array([1, 2, 3]), array([4, 5, 6])]
Split in 3 : [array([1, 2]), array([3, 4]), array([5, 6])]


## **2D Array**

In [91]:
var1 = np.array([[1,2],[3,4],[5,6]])

var_new = np.split(var1,3)
print(var_new)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


# **Numpy Array Functions**

---



## **Search Array**

> np.where()



In [94]:
var = np.array([1,2,3,9,1,5,6,4,8,7])
x = np.where(var==2)
print(x)

(array([1]),)


## **Search Sorted Array**

> np.searchsorted()

binary search karta hai aur index return karta hai jahan par hamari specified value insert hojaye aur array sorted hi rahe.


In [96]:
var = np.array([1,2,4,5,6])
x = np.searchsorted(var, 3)
print(x)

2


## **Sort Array**

> np.sort()


In [99]:
var = np.array([1,2,3,9,1,5,6,4,8,7])
print(np.sort(var))

[1 1 2 3 4 5 6 7 8 9]


## **Shuffle Array**

> np.random.shuffle()


In [103]:
var = np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[2 3 5 4 1]


## **Unique Array**

> np.unique()
union ke tarha same elements ko 1 baar likhta hai

In [108]:
var = np.array([1,2,3,9,1,5,6,4,8,7])
x = np.unique(var)
print(x)

[1 2 3 4 5 6 7 8 9]


## **Resize Array**

> np.resize()


In [109]:
var = np.array([1,2,3,4,5,6])
x = np.resize(var,(2,3))
print(x)

[[1 2 3]
 [4 5 6]]


## **Flatten / Ravel**

> np.flatten()

> np.ravel()

to convert multidimensional array to one dimension


In [115]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.flatten(order = "F"))
print(arr.ravel(order = "C"))

[1 4 2 5 3 6]
[1 2 3 4 5 6]


# **Insert and Delete Function**





```
 np.insert(array,2,"Shayan")

```


> array = array name

> 2 = insert position (index)

> "Shayan" = value







---



# **Insert**

In [116]:
arr = np.array(["khan","afridi"])
print(np.insert(arr,0,"shayan"))

['shayan' 'khan' 'afridi']


# **Delete**

In [128]:
arr = np.array(["shayan","khan","afridi"])
print(np.delete(arr,2))

['shayan' 'khan']


# **Matrix in Numpy Arrays**

---



```
  mx = np.matrix([[1,2,3],[4,5,6]])

```


---




## **Arithmetic Operation in Matrix**

### **Addition, Subtraction Same hi hoti hai array aur matrix me **

### **Multiplication**

> matrix.dot(matrix2)



In [118]:
mx1 = np.matrix([[1,2],[3,4]])
mx2 = np.matrix([[4,5],[6,7]])

print(mx1.dot(mx2))

[[16 19]
 [36 43]]


# **Matrix Functions**

---



## **1. Transpose**

> rows becomes columns and columns become rows



In [119]:
var = np.matrix([[1,2,3],[4,5,6]])
print(np.transpose(var))

[[1 4]
 [2 5]
 [3 6]]


## **2. Inverse**

> np.linalg.inv(arr)



In [126]:
arr = np.matrix([[1, 2], [3, 4]])
print(np.linalg.inv(arr))

[[-2.   1. ]
 [ 1.5 -0.5]]


## **3. Power**

> np.linalg.matrix_power(arr)



In [127]:
arr = np.matrix([[1, 2], [3, 4]])
print(np.linalg.matrix_power(arr,2))

[[ 7 10]
 [15 22]]


## **4. Determinant**

> np.linalg.det(arr)



In [125]:
arr = np.matrix([[1, 2], [3, 4]])
print(np.linalg.det(arr))

-2.0000000000000004
