

---


# **NumPy Practice Problems**


---



**Q-1** Create a 1D NumPy array from 1 to 20.
  *   Find its shape, size, and data type.
  *   Reverse the array without using loops.


In [166]:
import numpy as np

In [167]:
# Array create
arr = np.arange(1,21)
print("Array :",arr)

# part i
print("\nShape :",arr.shape)
print("Size :", arr.size)
print("Data type :",arr.dtype)

# part ii
print("\nReverse Array :",np.flip(arr))

Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Shape : (20,)
Size : 20
Data type : int64

Reverse Array : [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]




---



**Q-2** Generate a 2D array (3×4) filled with random integers (0–50).



*   Find the max, min, and mean.
*   Replace all even numbers with -1.



In [168]:
# Array Create
arr = np.random.randint(0,50,(3,4))
print("Original Array :\n",arr)

# Part i
print("\nMax :",arr.max())
print("Min :",arr.min())
print("Mean :",arr.mean())

# Part ii
arr[arr % 2 == 0] = -1
print("\nArray After:\n",arr)

Original Array :
 [[41 16  0 19]
 [ 2 14 12 12]
 [38 37 47 16]]

Max : 47
Min : 0
Mean : 21.166666666666668

Array After:
 [[41 -1 -1 19]
 [-1 -1 -1 -1]
 [-1 37 47 -1]]




---





**Q-3** Create a 5×5 identity matrix.



*   Change the diagonal values to 7.



In [169]:
# Array Create
arr = np.eye(5,5)
print("Original Identity Matrix :\n",arr)

# Part i
arr[arr == 1] = 7
print("\nArray After :\n",arr)

Original Identity Matrix :
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Array After :
 [[7. 0. 0. 0. 0.]
 [0. 7. 0. 0. 0.]
 [0. 0. 7. 0. 0.]
 [0. 0. 0. 7. 0.]
 [0. 0. 0. 0. 7.]]




---



**Q-4** Given arr = np.arange(1, 26).reshape(5,5)


*   Extract the 2nd column.
*   Extract the sub-matrix of last 3 rows & last 3 columns.
*   Replace the center element (row=3, col=3) with 999.









In [170]:
# Array Create
arr = np.arange(1, 26).reshape(5,5)
print("Original Array :\n",arr)

# Part i
print("\n2nd Column :",arr[:,1])

# part ii
print("\nsub-matrix of last 3 rows & last 3 columns :\n",arr[2:,2:])

# part iii
arr[2, 2] = 999
print("\n after replacing center element (row=3, col=3) with 999 :\n",arr)

Original Array :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

2nd Column : [ 2  7 12 17 22]

sub-matrix of last 3 rows & last 3 columns :
 [[13 14 15]
 [18 19 20]
 [23 24 25]]

 after replacing center element (row=3, col=3) with 999 :
 [[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12 999  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]]




---



**Q-5** Create an array of sales for 7 days: [250, 300, 270, 400, 325, 290, 310]


*   Find average, max, and min sales.
*   Which days had sales above average?
*   Increase sales by 10%.



In [171]:
# Array Create
arr = np.array([250, 300, 270, 400, 325, 290, 310])
print("Original Array :\n",arr)

# Part i
avg = np.mean(arr)
print("\nAverage Sales :",avg)
print("Max :",arr.max())
print("Min :",arr.min())

# Part ii
above_avg = np.where(arr>avg)[0]
print("\nSales Above Average :",above_avg)
print("Sales on those days :",arr[above_avg])

# Part iii
inc = arr * 1.10
print("\nSales after 10% increase :",inc)

Original Array :
 [250 300 270 400 325 290 310]

Average Sales : 306.42857142857144
Max : 400
Min : 250

Sales Above Average : [3 4 6]
Sales on those days : [400 325 310]

Sales after 10% increase : [275.  330.  297.  440.  357.5 319.  341. ]




---



**Q-6** Temperatures in Celsius: [36.5, 37.8, 39.2, 35.6, 38.1]


*   Convert to Fahrenheit.
*   Find which days indicate fever (≥ 37.5°C).






In [172]:
# Array Create
tc = np.array([36.5, 37.8, 39.2, 35.6, 38.1])
print("Temperature in Celsius :",tc)

# Part i
tf = (tc * (9/5) + 32)
print("\nTemperature in Fahrenheit :",tf)

# Part ii
temp_more = np.where(tc>=37.5)[0]
print("\nTemperature >= 37.5 (Index):",temp_more)
print("Temperature >= 37.5 (Values):",tc[temp_more])

Temperature in Celsius : [36.5 37.8 39.2 35.6 38.1]

Temperature in Fahrenheit : [ 97.7  100.04 102.56  96.08 100.58]

Temperature >= 37.5 (Index): [1 2 4]
Temperature >= 37.5 (Values): [37.8 39.2 38.1]




---



**Q-7** Create matrix A = [[2,1],[7,4]]


*   Find determinant, transpose, and inverse.
*   Compute A³.





In [173]:
# Create Matrix
mx = np.matrix([[2,1],[7,4]])
print("Original Matrix :\n",mx)

# Part i
print("\nDeterminant :",np.linalg.det(mx))
print("Transpose :\n",np.transpose(mx))
print("\nInverse :\n",np.linalg.inv(mx))

# Part ii
print("\nPower :\n",np.linalg.matrix_power(mx,3))

Original Matrix :
 [[2 1]
 [7 4]]

Determinant : 0.9999999999999996
Transpose :
 [[2 7]
 [1 4]]

Inverse :
 [[ 4. -1.]
 [-7.  2.]]

Power :
 [[ 64  35]
 [245 134]]




---



**Q-8** Solve the system of equations using NumPy:

2x + y = 5  
3x + 4y = 6



```
Isko matrix form me likh lete hain
            A⋅X=B
Where
        A=[23], X=[x​],B=[5​]
          ​[14​]    [y]   [6]
```



In [174]:
# Coefficient matrix
A = np.array([[2, 1],
              [3, 4]])

# Constants
B = np.array([5, 6])

# Solve Ax = B
solution = np.linalg.solve(A, B)

print("Solution [x, y] :", solution)

Solution [x, y] : [ 2.8 -0.6]




---



**Q-9** Student marks (5×3 matrix):



```
[[80, 90, 78],
 [88, 76, 92],
 [90, 85, 85],
 [70, 65, 60],
 [95, 100, 98]]
```

*   Find average marks of each student.
*   Find average in each subject.
*   Which student has the highest total?











In [175]:
mx = np.matrix([[80, 90, 78],
 [88, 76, 92],
 [90, 85, 85],
 [70, 65, 60],
 [95, 100, 98]])
print("Original Matrix :\n", mx)

# Average of Each Student
print("\nAverage of Each Student :\n",np.mean(mx,axis = 1))

# Average of Each Subject
print("\nAverage of Each Subject :\n",np.mean(mx,axis = 0))

# Student with Highest Total
total_of_students = np.sum(mx, axis=1)   # row-wise sum
highest_total = np.max(total_of_students)
student_index = np.argmax(total_of_students)  # index of student

print("\nHighest Total Marks :", highest_total)
print("Student with Highest Total (index):", student_index)

Original Matrix :
 [[ 80  90  78]
 [ 88  76  92]
 [ 90  85  85]
 [ 70  65  60]
 [ 95 100  98]]

Average of Each Student :
 [[82.66666667]
 [85.33333333]
 [86.66666667]
 [65.        ]
 [97.66666667]]

Average of Each Subject :
 [[84.6 83.2 82.6]]

Highest Total Marks : 293
Student with Highest Total (index): 4




---



**Q-10** Stock prices: [120, 125, 123, 130, 128]


*   Find daily changes.
*   Find percentage change.
*   Which day had max increase?









In [176]:
prices = np.array([120, 125, 123, 130, 128])
print("Stock Prices :", prices)

# Part i (Daily Changes)
changes = np.diff(prices)
print("Daily Changes :", changes)

# Part ii (Changes in Percentage)
percent_change = (changes / prices[:-1]) * 100
print("Percentage Change :", percent_change)

# Part iii (Day with Max Increase)
max_day = np.argmax(changes) + 1   # +1 because change belongs to next day
print("Day with Max Increase :", max_day)

Stock Prices : [120 125 123 130 128]
Daily Changes : [ 5 -2  7 -2]
Percentage Change : [ 4.16666667 -1.6         5.69105691 -1.53846154]
Day with Max Increase : 3




---



**Q-11** Simulate a 5×5 grayscale image with random values (0–255).


*   Find max, min, and mean brightness.






In [177]:
# 5×5 grayscale image with values 0–255
img = np.random.randint(0, 256, (5, 5))
print("Image:\n", img)

# Max, Min, Mean brightness
print("\nMax:", img.max())
print("Min:", img.min())
print("Mean:", img.mean())

Image:
 [[ 74  69 193  20  76]
 [148  72 245 179 246]
 [197 203 109  12 114]
 [ 40  80 174 249 189]
 [155 171   8  17 148]]

Max: 249
Min: 8
Mean: 127.52




---



**Q-12** Create a 3D array of shape (3,3,3).


*   Extract the 2nd matrix (all rows, all cols from depth=2).
*   Extract the diagonal of each matrix (depth-wise).






In [178]:
# Create 3D array (3×3×3)
arr = np.arange(1, 28).reshape(3,3,3)
print("3D Array:\n", arr)

# Part (i)
second_matrix = arr[1, :, :]   # all rows, all cols from depth=2
print("\n2nd Matrix (depth=2):\n", second_matrix)

# Part (ii)
diagonals = np.diagonal(arr, axis1=1, axis2=2)
print("\nDiagonals of each matrix (depth-wise):\n", diagonals)

3D Array:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

2nd Matrix (depth=2):
 [[10 11 12]
 [13 14 15]
 [16 17 18]]

Diagonals of each matrix (depth-wise):
 [[ 1  5  9]
 [10 14 18]
 [19 23 27]]




---



**Q-13** Given array:

```
arr = np.array([[1,2,3,3,1],
                [0,9,1,2,8],
                [1,2,3,8,8],
                [1,2,3,3,1]])
```
*   Find unique rows.
*   Find unique columns.







In [179]:
arr = np.array([[1,2,3,3,1],
                [0,9,1,2,8],
                [1,2,3,8,8],
                [1,2,3,3,1]])
print("Original Array :\n",arr)

#Unique Rows
unique_rows  = np.unique(arr,axis = 0)
print("\nUnique Rows :\n",unique_rows)

#Unique Columns
unique_cols = np.unique(arr,axis = 1)
print("\nUnique Columns :\n",unique_cols)

Original Array :
 [[1 2 3 3 1]
 [0 9 1 2 8]
 [1 2 3 8 8]
 [1 2 3 3 1]]

Unique Rows :
 [[0 9 1 2 8]
 [1 2 3 3 1]
 [1 2 3 8 8]]

Unique Columns :
 [[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
